### ISSUE TITLE
I want to enter the prediction code to "image-classifier.playground".

### ISSUE THREAD

**Issue by bemoregt** [krishkumar/createml-playgrounds#1]
HI, @krishkumar 

Is it possible that makes from "image-classifier.playground"  resemble to "movie-review-sentiment-classifier.playground "?

I want to enter the prediction code to "image-classifier.playground" look like "movie-review-sentiment-classifier.playground ".

Thanks in advance.

from @bemoregt.

**Comment by krishkumar** [comment]
Hi @bemoregt 

Yes. It is possible to automate the training. 

Check out - https://developer.apple.com/documentation/createml/creating_an_image_classifier_model

Section **Automate the Process of Building an Image Classifier** talks about this.
